apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv0001/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0001
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
