apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue-green
spec:
  type: NodePort
  selector:
    app: my-nginx
    role: blue
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
