apiVersion: v1
kind: Pod
metadata:
  name: my-init-pod
  labels:
    name: my-init-pod
spec:
  volumes:
    - name: html
      emptyDir: {}
  initContainers:
  - name: my-init-container
    image: alpine:3.15.0
    volumeMounts:
      - name:  html
        mountPath:  /html
    resources:
      limits:
        memory: "16Mi"
        cpu: "10m"
    command: ["/bin/sh", "-c", "echo '<h1>this is from init container</h1>' > html/index.html"]
  containers:
  - name: my-init-pod
    image: nginx:1.21.4-alpine
    volumeMounts:
      - name:  html
        mountPath:  /usr/share/nginx/html
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      periodSeconds: 5
      failureThreshold: 3
    ports:
      - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name:  my-init-pod-service
spec:
  selector:
    name:  my-init-pod
  type:  NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  80
    nodePort: 30000
