apiVersion: batch/v1
kind: CronJob
metadata:
  name:  my-cron-job
spec:
  concurrencyPolicy: Allow
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: my-cron-job
          labels:
            job: my-cron-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: my-cron-job
              image: alpine:3.15.0
              resources:
                limits:
                  memory: "16Mi"
                  cpu: "10m"
              command: ["sh", "-c", 'echo "doing my job $(date)"']