apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 5
  parallelism: 1
  activeDeadlineSeconds: 240
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: my-job
      labels:
        job: my-job
    spec:
      restartPolicy: Never
      containers:
      - name: my-job
        image: alpine:3.15.0
        resources:
          limits:
            memory: "16Mi"
            cpu: "10m"
        command: ["sh", "-c", 'echo "doing my job $(date)"']
